// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PACKET_SCHEMA_H_
#define FLATBUFFERS_GENERATED_PACKET_SCHEMA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace schema {

struct Entity;

struct Snapshot;
struct SnapshotBuilder;

struct Input;
struct InputBuilder;

struct Join;
struct JoinBuilder;

struct Leave;
struct LeaveBuilder;

struct Welcome;
struct WelcomeBuilder;

struct Packet;
struct PacketBuilder;

enum Payload : uint8_t {
  Payload_NONE = 0,
  Payload_Snapshot = 1,
  Payload_Input = 2,
  Payload_Join = 3,
  Payload_Leave = 4,
  Payload_Welcome = 5,
  Payload_MIN = Payload_NONE,
  Payload_MAX = Payload_Welcome
};

inline const Payload (&EnumValuesPayload())[6] {
  static const Payload values[] = {
    Payload_NONE,
    Payload_Snapshot,
    Payload_Input,
    Payload_Join,
    Payload_Leave,
    Payload_Welcome
  };
  return values;
}

inline const char * const *EnumNamesPayload() {
  static const char * const names[7] = {
    "NONE",
    "Snapshot",
    "Input",
    "Join",
    "Leave",
    "Welcome",
    nullptr
  };
  return names;
}

inline const char *EnumNamePayload(Payload e) {
  if (::flatbuffers::IsOutRange(e, Payload_NONE, Payload_Welcome)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPayload()[index];
}

template<typename T> struct PayloadTraits {
  static const Payload enum_value = Payload_NONE;
};

template<> struct PayloadTraits<schema::Snapshot> {
  static const Payload enum_value = Payload_Snapshot;
};

template<> struct PayloadTraits<schema::Input> {
  static const Payload enum_value = Payload_Input;
};

template<> struct PayloadTraits<schema::Join> {
  static const Payload enum_value = Payload_Join;
};

template<> struct PayloadTraits<schema::Leave> {
  static const Payload enum_value = Payload_Leave;
};

template<> struct PayloadTraits<schema::Welcome> {
  static const Payload enum_value = Payload_Welcome;
};

template <bool B = false>
bool VerifyPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Payload type);
template <bool B = false>
bool VerifyPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Entity FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t id_;
  float x_;
  float y_;
  float angle_;

 public:
  Entity()
      : id_(0),
        x_(0),
        y_(0),
        angle_(0) {
  }
  Entity(uint32_t _id, float _x, float _y, float _angle)
      : id_(::flatbuffers::EndianScalar(_id)),
        x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        angle_(::flatbuffers::EndianScalar(_angle)) {
  }
  uint32_t id() const {
    return ::flatbuffers::EndianScalar(id_);
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float angle() const {
    return ::flatbuffers::EndianScalar(angle_);
  }
};
FLATBUFFERS_STRUCT_END(Entity, 16);

struct Snapshot FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SnapshotBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TICK = 4,
    VT_ENTITIES = 6
  };
  uint64_t tick() const {
    return GetField<uint64_t>(VT_TICK, 0);
  }
  const ::flatbuffers::Vector<const schema::Entity *> *entities() const {
    return GetPointer<const ::flatbuffers::Vector<const schema::Entity *> *>(VT_ENTITIES);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TICK, 8) &&
           VerifyOffset(verifier, VT_ENTITIES) &&
           verifier.VerifyVector(entities()) &&
           verifier.EndTable();
  }
};

struct SnapshotBuilder {
  typedef Snapshot Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tick(uint64_t tick) {
    fbb_.AddElement<uint64_t>(Snapshot::VT_TICK, tick, 0);
  }
  void add_entities(::flatbuffers::Offset<::flatbuffers::Vector<const schema::Entity *>> entities) {
    fbb_.AddOffset(Snapshot::VT_ENTITIES, entities);
  }
  explicit SnapshotBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Snapshot> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Snapshot>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Snapshot> CreateSnapshot(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t tick = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const schema::Entity *>> entities = 0) {
  SnapshotBuilder builder_(_fbb);
  builder_.add_tick(tick);
  builder_.add_entities(entities);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Snapshot> CreateSnapshotDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t tick = 0,
    const std::vector<schema::Entity> *entities = nullptr) {
  auto entities__ = entities ? _fbb.CreateVectorOfStructs<schema::Entity>(*entities) : 0;
  return schema::CreateSnapshot(
      _fbb,
      tick,
      entities__);
}

struct Input FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InputBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FLAGS = 4,
    VT_TICK = 6
  };
  uint8_t flags() const {
    return GetField<uint8_t>(VT_FLAGS, 0);
  }
  uint64_t tick() const {
    return GetField<uint64_t>(VT_TICK, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_FLAGS, 1) &&
           VerifyField<uint64_t>(verifier, VT_TICK, 8) &&
           verifier.EndTable();
  }
};

struct InputBuilder {
  typedef Input Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_flags(uint8_t flags) {
    fbb_.AddElement<uint8_t>(Input::VT_FLAGS, flags, 0);
  }
  void add_tick(uint64_t tick) {
    fbb_.AddElement<uint64_t>(Input::VT_TICK, tick, 0);
  }
  explicit InputBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Input> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Input>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Input> CreateInput(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t flags = 0,
    uint64_t tick = 0) {
  InputBuilder builder_(_fbb);
  builder_.add_tick(tick);
  builder_.add_flags(flags);
  return builder_.Finish();
}

struct Join FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef JoinBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct JoinBuilder {
  typedef Join Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(Join::VT_ID, id, 0);
  }
  explicit JoinBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Join> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Join>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Join> CreateJoin(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0) {
  JoinBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct Leave FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LeaveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct LeaveBuilder {
  typedef Leave Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(Leave::VT_ID, id, 0);
  }
  explicit LeaveBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Leave> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Leave>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Leave> CreateLeave(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0) {
  LeaveBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct Welcome FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WelcomeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           verifier.EndTable();
  }
};

struct WelcomeBuilder {
  typedef Welcome Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(Welcome::VT_ID, id, 0);
  }
  explicit WelcomeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Welcome> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Welcome>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Welcome> CreateWelcome(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0) {
  WelcomeBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

struct Packet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  schema::Payload payload_type() const {
    return static_cast<schema::Payload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const schema::Snapshot *payload_as_Snapshot() const {
    return payload_type() == schema::Payload_Snapshot ? static_cast<const schema::Snapshot *>(payload()) : nullptr;
  }
  const schema::Input *payload_as_Input() const {
    return payload_type() == schema::Payload_Input ? static_cast<const schema::Input *>(payload()) : nullptr;
  }
  const schema::Join *payload_as_Join() const {
    return payload_type() == schema::Payload_Join ? static_cast<const schema::Join *>(payload()) : nullptr;
  }
  const schema::Leave *payload_as_Leave() const {
    return payload_type() == schema::Payload_Leave ? static_cast<const schema::Leave *>(payload()) : nullptr;
  }
  const schema::Welcome *payload_as_Welcome() const {
    return payload_type() == schema::Payload_Welcome ? static_cast<const schema::Welcome *>(payload()) : nullptr;
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyPayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const schema::Snapshot *Packet::payload_as<schema::Snapshot>() const {
  return payload_as_Snapshot();
}

template<> inline const schema::Input *Packet::payload_as<schema::Input>() const {
  return payload_as_Input();
}

template<> inline const schema::Join *Packet::payload_as<schema::Join>() const {
  return payload_as_Join();
}

template<> inline const schema::Leave *Packet::payload_as<schema::Leave>() const {
  return payload_as_Leave();
}

template<> inline const schema::Welcome *Packet::payload_as<schema::Welcome>() const {
  return payload_as_Welcome();
}

struct PacketBuilder {
  typedef Packet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(schema::Payload payload_type) {
    fbb_.AddElement<uint8_t>(Packet::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(Packet::VT_PAYLOAD, payload);
  }
  explicit PacketBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Packet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Packet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Packet> CreatePacket(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    schema::Payload payload_type = schema::Payload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  PacketBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

template <bool B>
inline bool VerifyPayload(::flatbuffers::VerifierTemplate<B> &verifier, const void *obj, Payload type) {
  switch (type) {
    case Payload_NONE: {
      return true;
    }
    case Payload_Snapshot: {
      auto ptr = reinterpret_cast<const schema::Snapshot *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_Input: {
      auto ptr = reinterpret_cast<const schema::Input *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_Join: {
      auto ptr = reinterpret_cast<const schema::Join *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_Leave: {
      auto ptr = reinterpret_cast<const schema::Leave *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Payload_Welcome: {
      auto ptr = reinterpret_cast<const schema::Welcome *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

template <bool B>
inline bool VerifyPayloadVector(::flatbuffers::VerifierTemplate<B> &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyPayload(
        verifier,  values->Get(i), types->GetEnum<Payload>(i))) {
      return false;
    }
  }
  return true;
}

inline const schema::Packet *GetPacket(const void *buf) {
  return ::flatbuffers::GetRoot<schema::Packet>(buf);
}

inline const schema::Packet *GetSizePrefixedPacket(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<schema::Packet>(buf);
}

template <bool B = false>
inline bool VerifyPacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<schema::Packet>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedPacketBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<schema::Packet>(nullptr);
}

inline void FinishPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schema::Packet> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPacketBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<schema::Packet> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace schema

#endif  // FLATBUFFERS_GENERATED_PACKET_SCHEMA_H_
